#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


if [ -z "${MYSQL_USER}" ]; then
    base_mysql_image_default_user='mysql'
    export MYSQL_USER="${base_mysql_image_default_user}"
fi
export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"

postgres_ready() {
python << END
import sys

import MySQLdb

try:
    MySQLdb.connect(
        host="${MYSQL_HOST}",
        port=int("${MYSQL_PORT}"),
        user="${MYSQL_USER}",
        password="${MYSQL_PASSWORD}",
        database="${MYSQL_DATABASE}",
    )
except Exception as error:
    print(error)
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for MariaDB to become available...'
  sleep 1
done
>&2 echo 'MariaDB is available'

exec "$@"
