# Generated by Django 3.0.10 on 2021-08-30 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='video_thumbs')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='VideoKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('event', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
                ('register_author', models.CharField(blank=True, max_length=500, null=True)),
                ('productor', models.CharField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('archivist_notes', models.TextField(blank=True, null=True)),
                ('documentary_unit', models.CharField(blank=True, max_length=500, null=True)),
                ('lang', models.CharField(blank=True, max_length=500, null=True)),
                ('original_format', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'video metadata',
                'verbose_name_plural': 'video metadatas',
            },
        ),
        migrations.CreateModel(
            name='VideoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='VideoSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('ini', models.TimeField()),
                ('end', models.TimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='videos.Video')),
            ],
            options={
                'verbose_name': 'video sequence',
                'verbose_name_plural': 'video sequences',
            },
        ),
        migrations.CreateModel(
            name='VideoProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('ply_embed_id', models.CharField(max_length=500)),
                ('plyr_provider', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='videos.Video')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='videos', to='videos.VideoCategory')),
                ('keywords', models.ManyToManyField(related_name='videos', to='videos.VideoKeyword')),
                ('people', models.ManyToManyField(related_name='videos', to='videos.VideoPerson')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categorization', to='videos.Video')),
            ],
            options={
                'verbose_name': 'video categorization',
                'verbose_name_plural': 'video categorizations',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='videos.VideoMeta'),
        ),
    ]
