# Generated by Django 3.0.10 on 2021-08-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
