# Generated by Django 3.0.10 on 2021-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='code',
            field=models.SlugField(unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbs', verbose_name='Thumb'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='videokeyword',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videokeyword',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videokeyword',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='videokeyword',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='archivist_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Archivist Notes'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='description_date',
            field=models.DateField(blank=True, null=True, verbose_name='Description Date'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='documentary_unit',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Documentary Unit'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='event',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='lang',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='original_format',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Original Format'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='productor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Productor'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='register_author',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Register Author'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='register_date',
            field=models.DateField(blank=True, null=True, verbose_name='Register Date'),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videoperson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='videoperson',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='videoperson',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='videoperson',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='videoprovider',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='videoprovider',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked at'),
        ),
        migrations.AlterField(
            model_name='videoprovider',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='videoprovider',
            name='ply_embed_id',
            field=models.CharField(max_length=500, verbose_name='Ply Embed ID'),
        ),
        migrations.AlterField(
            model_name='videoprovider',
            name='plyr_provider',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], max_length=50, verbose_name='Ply Provider'),
        ),
        migrations.AlterField(
            model_name='videosequence',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='videosequence',
            name='end',
            field=models.TimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='videosequence',
            name='ini',
            field=models.TimeField(verbose_name='Initiation'),
        ),
        migrations.AlterField(
            model_name='videosequence',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Title'),
        ),
    ]
