# Generated by Django 3.0.10 on 2021-08-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='description_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='register_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videometa',
            name='title',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
    ]
