# Generated by Django 3.0.10 on 2021-08-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210816_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprovider',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoprovider',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
