# Generated by Django 3.0.10 on 2021-08-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20210816_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprovider',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
