# Generated by Django 3.0.10 on 2021-08-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_videoprovider_checked_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocategory',
            options={'ordering': ['position'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='videokeyword',
            options={'ordering': ['position'], 'verbose_name': 'keyword', 'verbose_name_plural': 'keywords'},
        ),
        migrations.AlterModelOptions(
            name='videoperson',
            options={'ordering': ['position'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AddField(
            model_name='videocategory',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videokeyword',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoperson',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
