# Generated by Django 3.0.10 on 2021-08-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210823_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['code'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.RenameField(
            model_name='videometa',
            old_name='status',
            new_name='archivist_notes',
        ),
        migrations.AddField(
            model_name='videometa',
            name='documentary_unit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videometa',
            name='event',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videometa',
            name='lang',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videometa',
            name='original_format',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
