# Generated by Django 3.0.10 on 2021-08-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210825_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbs'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='videokeyword',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='videoperson',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
