version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  mariadb_data: {}

services:
  mariadb:
    image: mariadb:5.5
    container_name: killay_mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./.local.env

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: killay_local_django
    container_name: killay_django
    depends_on:
      - mariadb
    volumes:
      - .:/app:z
    env_file:
      - ./.local.env
    ports:
      - "7000:7000"
    command: /start

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: killay_local_node
    container_name: killay_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
