version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cmpirque_local_django
    container_name: cmpirque_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.local.env
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: cmpirque_local_postgres
    container_name: cmpirque_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.local.env

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: cmpirque_local_node
    container_name: cmpirque_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
