# Generated by Django 3.0.10 on 2022-01-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20210922_1552'),
        ('pages', '0002_add_initial_page_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='collection_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='videos.VideoCollection'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_title_visible_in_body',
            field=models.BooleanField(default=False, verbose_name='Is title visible in body'),
        ),
    ]
