# Generated by Django 3.2.18 on 2023-07-15 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_alter_piece_unique_together'),
        ('pages', '0004_alter_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='archives.archive'),
        ),
        migrations.AddField(
            model_name='page',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='archives.collection'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='page_images', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='kind',
            field=models.CharField(choices=[('PAGE', 'Page'), ('LINK', 'Link')], default='PAGE', max_length=10, verbose_name='Kind'),
        ),
    ]
