# Generated by Django 3.2.18 on 2023-07-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_alter_piece_unique_together'),
        ('pages', '0005_auto_20230715_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='archives.place'),
        ),
    ]
