# Generated by Django 3.2.20 on 2023-08-29 00:46

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_auto_20230828_1624'),
        ('pages', '0006_page_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='archive',
            field=models.ForeignKey(blank=True, help_text='Allows you to associate the page to a specific archive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='archives.archive', verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='page',
            name='body',
            field=django_quill.fields.QuillField(blank=True, help_text='Page body to render in HTML', null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='page',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Allows you to associate the page to a specific collection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='archives.collection', verbose_name='Collection'),
        ),
        migrations.AlterField(
            model_name='page',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image of the page', null=True, upload_to='page_images', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_title_visible_in_body',
            field=models.BooleanField(default=False, help_text='Indicates whether a page title appears in the body', verbose_name='Is title visible in body'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Indicates if the page will be visible to the public', verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_visible_in_footer',
            field=models.BooleanField(default=False, help_text='Indicates whether a page link appears in the footer', verbose_name='Is visible in footer'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_visible_in_navbar',
            field=models.BooleanField(default=False, help_text='Indicates whether a page link appears in the navigation bar', verbose_name='Is visible in navbar'),
        ),
        migrations.AlterField(
            model_name='page',
            name='kind',
            field=models.CharField(choices=[('PAGE', 'Page'), ('LINK', 'Link')], default='PAGE', help_text='Kind of the page (page or redirect to link)', max_length=10, verbose_name='Kind'),
        ),
        migrations.AlterField(
            model_name='page',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Allows you to associate the page to a specific place', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='archives.place', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='page',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Determines the position in which it will be displayed, the smaller the number, the earlier it will be located', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='page',
            name='redirect_to',
            field=models.URLField(blank=True, help_text='URL to be redirected', null=True, verbose_name='Redirect to'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='Slug of the page, must be unique in the site', max_length=150, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title of the page', max_length=150, verbose_name='Title'),
        ),
    ]
