# Generated by Django 3.0.10 on 2021-08-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
