# Generated by Django 3.0.10 on 2021-09-05 01:33

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_initial_page_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
