# Generated by Django 3.0.10 on 2021-09-17 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_add_initial_admin_configuration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['position'], 'verbose_name': 'social media', 'verbose_name_plural': 'social medias'},
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='css_class',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_is_visible',
            field=models.BooleanField(default=True, verbose_name='Footer is visible'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='domain',
            field=models.CharField(default='killay-site.com', max_length=250, verbose_name='Domain'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='name',
            field=models.CharField(default='Killay Site Name', max_length=250, verbose_name='Name of Site'),
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='logos', verbose_name='Image')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Is visible')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='admin.SiteConfiguration')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
                'ordering': ['position'],
            },
        ),
    ]
