# Generated by Django 3.0.10 on 2022-01-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_add_initial_admin_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='collection_site',
            field=models.BooleanField(default=False, verbose_name='Collection site'),
        ),
    ]
