# Generated by Django 3.2.20 on 2023-08-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20230807_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(help_text='Logo image', upload_to='logos', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Indicates if the logo will be visible to the public', verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.CharField(help_text='Name of the logo', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Determines the position in which it will be displayed, the smaller the number, the earlier it will be located', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='Indicates if the social network will be visible to the public', verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Determines the position in which it will be displayed, the smaller the number, the earlier it will be located', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('vimeo', 'Vimeo')], help_text='Social network provider', max_length=150, verbose_name='Provider'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.URLField(help_text='Social network profile URL', verbose_name='URL'),
        ),
    ]
