# Generated by Django 3.0.10 on 2021-09-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Code')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='video_thumbs', verbose_name='Thumb')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VideoCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_collections', to='sites.Site')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['position', 'slug'],
                'unique_together': {('slug', 'site')},
            },
        ),
        migrations.CreateModel(
            name='VideoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('event', models.CharField(blank=True, max_length=500, null=True, verbose_name='Event')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_date', models.DateField(blank=True, null=True, verbose_name='Description Date')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Location')),
                ('duration', models.TimeField(blank=True, null=True, verbose_name='Duration')),
                ('register_date', models.DateField(blank=True, null=True, verbose_name='Register Date')),
                ('register_author', models.CharField(blank=True, max_length=500, null=True, verbose_name='Register Author')),
                ('productor', models.CharField(blank=True, max_length=500, null=True, verbose_name='Productor')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('archivist_notes', models.TextField(blank=True, null=True, verbose_name='Archivist Notes')),
                ('documentary_unit', models.CharField(blank=True, max_length=500, null=True, verbose_name='Documentary Unit')),
                ('lang', models.CharField(blank=True, max_length=500, null=True, verbose_name='Language')),
                ('original_format', models.CharField(blank=True, max_length=500, null=True, verbose_name='Original Format')),
            ],
            options={
                'verbose_name': 'video metadata',
                'verbose_name_plural': 'video metadatas',
            },
        ),
        migrations.CreateModel(
            name='VideoSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('ini', models.TimeField(verbose_name='Initiation')),
                ('end', models.TimeField(verbose_name='End')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='videos.Video')),
            ],
            options={
                'verbose_name': 'video sequence',
                'verbose_name_plural': 'video sequences',
                'ordering': ['ini'],
            },
        ),
        migrations.CreateModel(
            name='VideoProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('online', models.BooleanField(default=False, verbose_name='Online')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Checked at')),
                ('ply_embed_id', models.CharField(max_length=500, verbose_name='Ply Embed ID')),
                ('plyr_provider', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], max_length=50, verbose_name='Ply Provider')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='videos.Video')),
            ],
            options={
                'verbose_name': 'video provider',
                'verbose_name_plural': 'video provider',
            },
        ),
        migrations.CreateModel(
            name='VideoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_people', to='videos.VideoCollection', verbose_name='Collection')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_people', to='sites.Site')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ['position', 'slug'],
                'unique_together': {('slug', 'site')},
            },
        ),
        migrations.CreateModel(
            name='VideoKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_keywords', to='videos.VideoCollection', verbose_name='Collection')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_keywords', to='sites.Site')),
            ],
            options={
                'verbose_name': 'keyword',
                'verbose_name_plural': 'keywords',
                'ordering': ['position', 'slug'],
                'unique_together': {('slug', 'site')},
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_categories', to='videos.VideoCollection', verbose_name='Collection')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_categories', to='sites.Site')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['collection', 'position', 'slug'],
                'unique_together': {('slug', 'collection'), ('slug', 'site')},
            },
        ),
        migrations.CreateModel(
            name='VideoCategorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='videos', to='videos.VideoCategory', verbose_name='Categories')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.VideoCollection', verbose_name='Collections')),
                ('keywords', models.ManyToManyField(related_name='videos', to='videos.VideoKeyword', verbose_name='Keywords')),
                ('people', models.ManyToManyField(related_name='videos', to='videos.VideoPerson', verbose_name='People')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categorization', to='videos.Video')),
            ],
            options={
                'verbose_name': 'video categorization',
                'verbose_name_plural': 'video categorizations',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='meta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='videos.VideoMeta'),
        ),
        migrations.AddField(
            model_name='video',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sites.Site'),
        ),
    ]
