# Generated by Django 3.0.10 on 2021-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210920_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocollection',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together={('slug', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='videokeyword',
            unique_together={('slug', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='videoperson',
            unique_together={('slug', 'collection')},
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='site',
        ),
        migrations.RemoveField(
            model_name='videokeyword',
            name='site',
        ),
        migrations.RemoveField(
            model_name='videoperson',
            name='site',
        ),
    ]
