# Generated by Django 3.2.21 on 2023-12-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_page_collection_site'),
        ('videos', '0004_auto_20230504_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocategorization',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='videocategorization',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='videocategorization',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='videocategorization',
            name='people',
        ),
        migrations.RemoveField(
            model_name='videocategorization',
            name='video',
        ),
        migrations.AlterUniqueTogether(
            name='videocategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='videocollection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videocollection',
            name='site',
        ),
        migrations.AlterUniqueTogether(
            name='videokeyword',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videokeyword',
            name='collection',
        ),
        migrations.AlterUniqueTogether(
            name='videoperson',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='videoperson',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='videoprovider',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videosequence',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoCategorization',
        ),
        migrations.DeleteModel(
            name='VideoCategory',
        ),
        migrations.DeleteModel(
            name='VideoCollection',
        ),
        migrations.DeleteModel(
            name='VideoKeyword',
        ),
        migrations.DeleteModel(
            name='VideoMeta',
        ),
        migrations.DeleteModel(
            name='VideoPerson',
        ),
        migrations.DeleteModel(
            name='VideoProvider',
        ),
        migrations.DeleteModel(
            name='VideoSequence',
        ),
    ]
