# Generated by Django 3.2.18 on 2023-05-26 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_auto_20230524_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('allowed_archives', models.ManyToManyField(related_name='allowed_places', to='archives.Archive', verbose_name='Allowed Places')),
                ('allowed_collections', models.ManyToManyField(related_name='allowed_places', to='archives.Collection', verbose_name='Allowed Places')),
                ('allowed_pieces', models.ManyToManyField(related_name='allowed_places', to='archives.Piece', verbose_name='Allowed Places')),
            ],
            options={
                'verbose_name': 'place',
                'verbose_name_plural': 'places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('ipv4', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP Address')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='archives.place')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['ipv4'],
            },
        ),
    ]
