# Generated by Django 3.2.18 on 2023-05-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_place_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='is_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archive',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
