# Generated by Django 3.2.18 on 2023-07-15 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('archives', '0006_alter_category_collection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='piece',
            unique_together={('code', 'site')},
        ),
    ]
