# Generated by Django 3.0.10 on 2021-08-27 03:52

from django.db import migrations
from django.conf import settings


def create_initial_adminconfig(apps, schema_editor):
    SiteConfiguration = apps.get_model("admin", "SiteConfiguration")
    SiteConfiguration.objects.update_or_create(id=settings.SITE_ID)


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_adminconfig),
    ]
