# Generated by Django 3.0.10 on 2021-08-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_add_initial_admin_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('youtube', 'Youtube'), ('vimeo', 'Vimeo')], default='youtube', max_length=150),
            preserve_default=False,
        ),
    ]
