# Generated by Django 3.0.10 on 2021-09-03 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_siteconfiguration_footer_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='logos', verbose_name='Image')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Is visible')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='admin.SiteConfiguration')),
            ],
        ),
    ]
