name: django CD

on:
  push:
    branches:
      - devel

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy Webhook
      - uses: fjogeleit/http-request-action@v1
        with:
          url: {{ secrets.DEPLOY_WEBHOOK_URL }}
          method: 'POST'
