
name: django CI

on:
  pull_request:
    branches:
      - devel
      - master
  push:
    branches:
      - devel
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: github_actions
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432 # exposing 5432 port for application to use
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python environment # setting python environment to 3.6.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.6.8'
      - name: check python version # checking the python version to see if 3.6.8 is installed.
        run: python --version
      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
      - name: install requirements # install application requirements
        run: pip install -r requirements/local.txt
      - name: check pre-commit # check code formatting
        run: pre-commit run --all-files
      - name: run migrations # run migrations to create table in side car db container
        run: python manage.py migrate
      - name: run coverage & pytest # running tests
        run: coverage run -m pytest && coverage report -m
