
name: django CI

on:
  pull_request:
    branches:
      - devel
      - master
  push:
    branches:
      - devel
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_DATABASE: github_actions
          MYSQL_PASSWORD: mariadb
          MYSQL_USER: mariadb
          MYSQL_ROOT_PASSWORD: mariadb
        ports:
          - 3306:3306 # exposing 5432 port for application to use
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    env:
      DATABASE_URL: mysql://mariadb:mariadb@127.0.0.1:3306/github_actions
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: setup python environment # setting python environment to 3.6.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: check python version # checking the python version to see if 3.6.8 is installed.
        run: python --version
      - name: mariadb prerequisites
        run: sudo apt-get install -y libmariadbclient-dev
      - name: install requirements # install application requirements
        run: pip install -r requirements/local.txt
      - name: check pre-commit # check code formatting
        run: pre-commit run --all-files
      - name: run coverage & pytest # running tests
        run: coverage run -m pytest && coverage report -m
