# Generated by Django 3.2.18 on 2023-05-30 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin', '0004_auto_20230504_1406'),
        ('archives', '0005_auto_20230529_1101'),
        ('pages', '0003_auto_20220110_0653'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('ALL', 'All'), ('ONE_ARCHIVE', 'One Archive'), ('ONE_COLLECTION', 'One Collection')], default='ALL', max_length=50, verbose_name='Scope')),
                ('home', models.CharField(choices=[('PAGE', 'Page'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=50, verbose_name='Home')),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='admin.siteconfiguration')),
                ('home_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer', to='pages.page')),
                ('scope_archive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer', to='archives.archive')),
                ('scope_collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer', to='archives.collection')),
            ],
        ),
        migrations.CreateModel(
            name='ContentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_stats', to='viewer.viewer')),
            ],
        ),
    ]
