# Generated by Django 3.2.20 on 2023-08-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_auto_20230828_1624'),
        ('pages', '0006_page_place'),
        ('viewer', '0002_add_initial_viewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='home',
            field=models.CharField(choices=[('PAGE', 'Page'), ('DEFAULT', 'Default')], default='DEFAULT', help_text='Indicates if the home page will be used by default (depending on the scope) or a specific page will be assigned', max_length=50, verbose_name='Home'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='home_page',
            field=models.ForeignKey(help_text='In case of selecting the home by page this must be selected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer', to='pages.page'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='scope',
            field=models.CharField(choices=[('ALL', 'All'), ('ONE_ARCHIVE', 'One Archive'), ('ONE_COLLECTION', 'One Collection')], default='ALL', help_text='Determines the scope of the content to be viewed by the public, which can be reduced to a single archive or collection', max_length=50, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='scope_archive',
            field=models.ForeignKey(help_text='In case of selecting the scope in a single archive, the archive must be specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer', to='archives.archive'),
        ),
        migrations.AlterField(
            model_name='viewer',
            name='scope_collection',
            field=models.ForeignKey(help_text='In case of selecting the scope in a single collection, the collection must be specified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewer', to='archives.collection'),
        ),
    ]
